#!/usr/bin/env bash
# Generate install/chisel.config and install/test_filter.config from *.in templates.
# Substitutes @CHISEL_ROOT@ with the absolute Chisel repository path.
#
# Usage: install/gen_config.sh <CHISEL_dir>

set -euo pipefail

die() { echo "[gen_config] ERROR: $*" >&2; exit 1; }

[[ $# -eq 1 ]] || die "usage: $0 <CHISEL_dir>"
[[ -d "$1" ]] || die "not a directory: $1"

CHISEL_ROOT="$(cd "$1" && pwd)"
INSTALL="${CHISEL_ROOT}/install"

subst_root() {
  sed "s|@CHISEL_ROOT@|${CHISEL_ROOT}|g"
}

gen_one() {
  local src="$1"
  local dest="$2"
  local title="${3:-}"
  local tmp
  [[ -f "$src" ]] || die "missing template: $src"
  subst_root < "$src" > "$dest"
  if [[ -n "$title" ]]; then
    tmp="$(mktemp "${dest}.XXXXXX")"
    { echo "# ${title}"; tail -n +2 "$dest"; } > "$tmp"
    mv "$tmp" "$dest"
  fi
  echo "[gen_config] wrote ${dest}"
}

gen_one "${INSTALL}/chisel.config.in" "${INSTALL}/chisel.config" "chisel.config — generated by make config (do not commit)"
gen_one "${INSTALL}/test_filter.config.in" "${INSTALL}/test_filter.config" "test_filter.config — generated by make config (do not commit)"
